Replace rnix-lsp with nixd
As it turns out, rnix-lsp has been archived [1] and will be removed from
nixpkgs [2].

[1]: https://github.com/nix-community/rnix-lsp
[2]: https://github.com/NixOS/nixpkgs/pull/294488

Context

With the last `nix flake update`, home-manager failed to build new
generations with the following error message:

    error: Package ‘nix-2.15.3’ in
    /nix/store/...-source/pkgs/tools/package-management/nix/common.nix:249
    is marked as insecure, refusing to evaluate.

As it turns out, rnix-lsp is the culprit pulling in this ancient Nix
version.

Signed-off-by: Manuel Hutter <manuel@hutter.io>